import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { AnimatePresence } from "framer-motion";
import {motion as m } from "framer-motion"
import Navbar from './Navbar'

const App = () =>{
    return (
        <>
            <Navbar/>
            <AnimatePresence mode={"wait"}>
            <m.div
        initial = {{y: "100%" }}
        animate = {{y: "0%" }}
        transition = {{duration:0.75, ease: "easeOut" }}
        exit={{ opacity:1}}
        className={styles.bgcolor1}
        > 
      <div   
      className={styles.container} >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.titlebox} >
            <h1 className={styles.h1}>Guardians of the Galaxy vol. 1</h1>
          </div>
          <div className={styles.titlebox}>
            <h1 className={styles.h1}>Guardians of the Galaxy vol. 2</h1>
          </div>
        </main>
      </div>
            </m.div>
            </AnimatePresence>   
        </>
  )
}

export default App;