import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Contact(){
    return(
        <div>
            <Head>
                <title>contact page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.h1}>Contact</h1>
            </main>
        </div>
    )
}