import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {motion as m } from "framer-motion"

export default function Contact(){
    return(
        <m.div
        initial = {{y: "100%" }}
        animate = {{y: "0%" }}
        transition = {{duration:0.75, ease: "easeOut" }}
        exit={{ opacity:1}} 
        className = {styles.bgcolor2} 
        >    
            <Head>
                <title>Contact Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.titlebox}>
                    <h1 className={styles.h1}>Contact</h1>
                </div>
                <div className={styles.titlebox}>
                    <h1 className={styles.h1}>Contact</h1>
                </div>
            </main>
        </m.div>
    )
}